### ISSUE TITLE
几处疑问

### ISSUE THREAD

**Issue by nita22** [geekidea/update-record#1]
1、UpdateRecordComparator.compare方法中存在重复设置updateRecordColumnLog.setBeforeVersion(beforeVersionValue)
updateRecordColumnLog..setAfterVersion(afterVersionValue)
2、UpdateRecordAopSupport.save中format参数未用到
3、UpdateRecordComparator.compare方法中，有另外一种做法：
可以将string存放至ArrayList里面，然后再join，这样就不用每个加分隔符，再删掉最后一个分隔符了
4、update_record_log、update_record_table_log、update_record_column_log都是每次变更新增一行数据，那update_time字段意义就不大了

**Comment by springboot-plus** [comment]
1. 这张表中记录字段变化，前后版本是存在冗余，方便查看用
updateRecordColumnLog.setBeforeVersion(beforeVersionValue)
updateRecordColumnLog..setAfterVersion(afterVersionValue)
2. UpdateRecordAopSupport.save中format参数未用到，已修复
3. 分隔符方式，已优化
4. update_time在代码层面不会修改，这里的意义是，可以在mysql中设置列有修改，自动变化修改时间用。
